import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

const AQUA_GRADIENT = Platform.OS === "web"
  ? "linear-gradient(90deg, #00bcd4 0%, #3a3fbd 100%)"
  : "#00bcd4";

const styles = StyleSheet.create({
  // General containers
  startingPage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e0f7fa",
    overflow: "hidden",
  },
  languageSelection: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e0f7fa",
    overflow: "hidden",
  },
  homePage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e0f7fa",
    overflow: "hidden",
  },
  waterQualityPage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e0f7fa",
    overflow: "hidden",
  },
  emptyPage: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e0f7fa",
    overflow: "hidden",
  },

  // Glassmorphism card for main content
  glassCard: {
    width: "94%",
    maxWidth: 370,
    alignItems: "center",
    paddingVertical: 18,
    paddingHorizontal: 10,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.07)", // Even more transparent
    borderWidth: 1.2,
    borderColor: "rgba(255,255,255,0.18)",
    shadowColor: "#009688",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },

  // Animated background bubbles for texture
  bubble1: {
    position: "absolute",
    top: -60,
    left: -60,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "#b2ebf2",
    opacity: 0.45,
    zIndex: 0,
  },
  bubble2: {
    position: "absolute",
    bottom: -80,
    right: -80,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#4dd0e1",
    opacity: 0.35,
    zIndex: 0,
  },
  bubble3: {
    position: "absolute",
    top: height * 0.5,
    left: -40,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#00bcd4",
    opacity: 0.18,
    zIndex: 0,
  },

  // Logo
  logo: {
    marginBottom: 18,
    width: 120,
    height: 120,
    resizeMode: "contain",
    shadowColor: "#00bcd4",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },

  // Typography
  appName: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#00796b",
    letterSpacing: 2,
    marginBottom: 8,
    fontFamily: Platform.OS === "ios" ? "AvenirNext-DemiBold" : "sans-serif-medium",
    textShadowColor: "#b2ebf2",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  appDescription: {
    fontSize: 18,
    color: "#006064",
    marginBottom: 32,
    textAlign: "center",
    fontFamily: Platform.OS === "ios" ? "AvenirNext-Regular" : "sans-serif",
    opacity: 0.85,
  },
  heading: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 40,
    textAlign: "center",
    color: "#00796b",
    letterSpacing: 1,
    textShadowColor: "#b2ebf2",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },

  // Buttons
  button: {
    backgroundColor: AQUA_GRADIENT,
    borderRadius: 24,
    paddingVertical: 10, // reduced for mobile
    paddingHorizontal: 18, // reduced for mobile
    alignItems: "center",
    shadowColor: "#009688",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
    marginTop: 8,
  },
  buttonPressed: {
    backgroundColor: "#009688",
  },
  buttonText: {
    color: "#00796b", // or "#009688"
    fontSize: 20,
    fontWeight: "bold",
    letterSpacing: 1,
    fontFamily: Platform.OS === "ios" ? "AvenirNext-DemiBold" : "sans-serif-medium",
    textShadowColor: "#fff",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  bigHomeButton: {
    width: "100%",
    minWidth: 180,
    maxWidth: 340,
    marginVertical: 10,
    paddingVertical: 22,
    borderRadius: 24,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 6,
    backgroundColor: "transparent", // Fix: no background by default
  },
  bigHomeButtonText: {
    fontSize: 24,
    fontWeight: "bold",
    letterSpacing: 1,
    fontFamily: Platform.OS === "ios" ? "AvenirNext-DemiBold" : "sans-serif-medium",
    textShadowColor: "#b2ebf2",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  buttonNext: {
    backgroundColor: "#3a3fbd",
    padding: 8,
    borderRadius: 15,
    width: 100,
    alignItems: "center",
    marginTop: 10,
  },
  button1: {
    backgroundColor: "#3a3fbd",
    padding: 10,
    borderRadius: 15,
    width: 250,
    marginTop: 10,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  button2: {
    backgroundColor: "#497838",
    padding: 10,
    borderRadius: 15,
    width: 250,
    marginTop: 10,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  button4: {
    backgroundColor: "#497838",
    padding: 15,
    borderRadius: 15,
    width: 250,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  alterButton: {
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 15,
    width: 250,
    borderWidth: 3,
    borderColor: "#3a3fbd",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  alterbuttonText: {
    color: "#3a3fbd",
    fontSize: 20,
    textAlign: "center",
    fontWeight: "bold",
  },
  buttonText1: {
    color: "white",
    fontSize: 18,
    textAlign: "center",
  },

  // Table styles
  tableContainer: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
    backgroundColor: "rgba(255,255,255,0.7)",
    marginBottom: 16,
  },
  tableRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    paddingVertical: 10,
  },
  tableHeader: {
    width: "40%",
    fontWeight: "italic",
    paddingHorizontal: 10,
    color: "#00796b",
    fontSize: 16,
  },
  tableCell: {
    width: "30%",
    paddingHorizontal: 10,
    color: "#006064",
    fontSize: 15,
  },
  tableCell0: {
    flex: 1,
    padding: 10,
    borderRightWidth: 1,
    borderColor: "black",
  },
  viewDetailsButton: {
    backgroundColor: "#3a3fbd",
    padding: 10,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  viewDetailsButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
  },
  tableHeader0: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#00796b",
  },
  tableData0: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#006064",
  },

  // Input and data containers
  inputContainer: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.5)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  mainContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#e0f7fa",
  },
  headerContainer0: {
    marginBottom: 10,
    alignItems: "center",
  },
  headerText0: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 60,
    textAlign: "center",
    color: "#00796b",
  },
  buttonSection: {
    marginBottom: 20,
  },
  button0: {
    width: 200,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#00bcd4",
    marginBottom: 10,
  },
  buttonText0: {
    fontSize: 18,
    color: "#fff",
  },
  dataSection: {
    marginBottom: 20,
  },
  dataContainer: {
    width: 300,
    minHeight: 100,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.7)",
    borderRadius: 16,
    padding: 30,
    shadowColor: "#00bcd4",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 5,
    marginBottom: 16,
  },
  dataLabel: {
    fontSize: 18,
    marginBottom: 10,
    textAlign: "center",
    color: "#006064",
  },
  dataValue: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    color: "#00796b",
  },

  // Modal and stat card styles for Data Summary
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(30, 40, 80, 0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCard: {
    width: 340,
    backgroundColor: "rgba(255,255,255,0.85)",
    borderRadius: 24,
    padding: 20,
    alignItems: "center",
    shadowColor: "#3a3fbd",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
  },
  modalClose: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 10,
    padding: 4,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#3a3fbd",
    marginBottom: 18,
    marginTop: 2,
    textAlign: "center",
  },
  statRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 8,
  },
  statCard: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "rgba(230,240,255,0.7)",
    marginHorizontal: 4,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 2,
    minWidth: 80,
  },
  statLabel: {
    fontSize: 13,
    color: "#3a3fbd",
    fontWeight: "bold",
    marginTop: 2,
    marginBottom: 1,
    textAlign: "center",
  },
  statValue: {
    fontSize: 16,
    color: "#222",
    fontWeight: "bold",
    marginTop: 2,
    textAlign: "center",
  },
});

export default styles;